language: python
python:
  - "2.7"
install:
  - pip --default-timeout=180 install -r requirements.txt
  - pip --default-timeout=180 install -r test_requirements.txt
  - 'if [[ "$TRAVIS_PYTHON_VERSION" != "pypy" ]]; then pip install psycopg2; fi'
before_script:
  - psql -c 'create database lastuser_test_app;' -U postgres

script:
  - nosetests --with-timer

notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
