language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip --default-timeout=180 install -r requirements.txt --use-mirrors
  - pip --default-timeout=180 install -r test_requirements.txt --use-mirrors
before_script:
  - psql -c 'create database coaster;' -U postgres
script:
  - nosetests tests --with-coverage
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
